# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testNotepad.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuZoom = QtWidgets.QMenu(self.menuView)
        self.menuZoom.setObjectName("menuZoom")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPage_Setup = QtWidgets.QAction(MainWindow)
        self.actionPage_Setup.setObjectName("actionPage_Setup")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSearch_with = QtWidgets.QAction(MainWindow)
        self.actionSearch_with.setObjectName("actionSearch_with")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_Next = QtWidgets.QAction(MainWindow)
        self.actionFind_Next.setObjectName("actionFind_Next")
        self.actionFind_Previous = QtWidgets.QAction(MainWindow)
        self.actionFind_Previous.setObjectName("actionFind_Previous")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionGo_To = QtWidgets.QAction(MainWindow)
        self.actionGo_To.setObjectName("actionGo_To")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionTime_Date = QtWidgets.QAction(MainWindow)
        self.actionTime_Date.setObjectName("actionTime_Date")
        self.actionWord_Wrap = QtWidgets.QAction(MainWindow)
        self.actionWord_Wrap.setObjectName("actionWord_Wrap")
        self.actionFont = QtWidgets.QAction(MainWindow)
        self.actionFont.setObjectName("actionFont")
        self.actionStatus_Bar = QtWidgets.QAction(MainWindow)
        self.actionStatus_Bar.setObjectName("actionStatus_Bar")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionRestore_Default_Zoom = QtWidgets.QAction(MainWindow)
        self.actionRestore_Default_Zoom.setObjectName("actionRestore_Default_Zoom")
        self.actionView_Help = QtWidgets.QAction(MainWindow)
        self.actionView_Help.setObjectName("actionView_Help")
        self.actionSend_Feedback = QtWidgets.QAction(MainWindow)
        self.actionSend_Feedback.setObjectName("actionSend_Feedback")
        self.actionAbout_Notepad = QtWidgets.QAction(MainWindow)
        self.actionAbout_Notepad.setObjectName("actionAbout_Notepad")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionNew_Window)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPage_Setup)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSearch_with)
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionFind_Next)
        self.menuEdit.addAction(self.actionFind_Previous)
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addAction(self.actionGo_To)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionTime_Date)
        self.menuFormat.addAction(self.actionWord_Wrap)
        self.menuFormat.addAction(self.actionFont)
        self.menuZoom.addAction(self.actionZoom_In)
        self.menuZoom.addAction(self.actionZoom_Out)
        self.menuZoom.addAction(self.actionRestore_Default_Zoom)
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menuView.addAction(self.actionStatus_Bar)
        self.menuHelp.addAction(self.actionView_Help)
        self.menuHelp.addAction(self.actionSend_Feedback)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Notepad)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFormat.setTitle(_translate("MainWindow", "Format"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuZoom.setTitle(_translate("MainWindow", "Zoom"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionPage_Setup.setText(_translate("MainWindow", "Page Setup"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSearch_with.setText(_translate("MainWindow", "Search with browser"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFind_Next.setText(_translate("MainWindow", "Find Next"))
        self.actionFind_Previous.setText(_translate("MainWindow", "Find Previous"))
        self.actionReplace.setText(_translate("MainWindow", "Replace"))
        self.actionGo_To.setText(_translate("MainWindow", "Go To"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionTime_Date.setText(_translate("MainWindow", "Time/Date"))
        self.actionWord_Wrap.setText(_translate("MainWindow", "Word Wrap"))
        self.actionFont.setText(_translate("MainWindow", "Font"))
        self.actionStatus_Bar.setText(_translate("MainWindow", "Status Bar"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionRestore_Default_Zoom.setText(_translate("MainWindow", "Restore Default Zoom"))
        self.actionView_Help.setText(_translate("MainWindow", "View Help"))
        self.actionSend_Feedback.setText(_translate("MainWindow", "Send Feedback"))
        self.actionAbout_Notepad.setText(_translate("MainWindow", "About Notepad"))

